POST http://127.0.0.1:3333/api/downloadFile HTTP/1.1
content-type: application/json

{
    "fileName": "gitTest/1/nesANN/README.md"
}

###

POST http://127.0.0.1:3333/api/saveFile HTTP/1.1
content-type: application/json

{
    "fileName": "gitTest/1/nesANN/test/testFile.txt",
    "data": "testing Stuff2"
}

###

POST http://127.0.0.1:3333/api/createDirectory HTTP/1.1
content-type: application/json

{
    "directoryName": "gitTest/1/nesANN/test"
}

###

DELETE http://127.0.0.1:3333/api/deleteDirectory HTTP/1.1
content-type: application/json

{
    "name": "gitTest/1/nesANN/test"
}